name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  deployments: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: NuGet/setup-nuget@v1

    - uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "~3.25.0"
        ninjaVersion: "^1.11.1"

    - uses: TheMrMilchmann/setup-msvc-dev@v2
      with:
        arch: x64

    - name: Install Dependencies
      run: |
        nuget install Microsoft.VSSDK.Debugger.VSDebugEng -Version 17.0.2012801
        nuget install Microsoft.VSSDK.Debugger.VSDConfigTool -Version 17.0.2012801

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH="${{ github.workspace }}\Microsoft.VSSDK.Debugger.VSDebugEng.17.0.2012801\build\native;${{ github.workspace }}\Microsoft.VSSDK.Debugger.VSDConfigTool.17.0.2012801\build"

    - name: Build
      run: |
        cd build
        ninja

    - name: Add build info
      run: |
        "ref:    ${{ github.ref_name }}`n" + `
        "commit: ${{ github.sha }}`n"  + `
        "date:   $(Get-Date -UFormat '%FT%T%Z' -AsUTC)" | Out-File -Path "${{ github.workspace }}/build/bin/info.txt"

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: childdebugger-concord-x86_64-windows
        path: |
          ${{ github.workspace }}/build/bin/ChildDebugger.dll
          ${{ github.workspace }}/build/bin/ChildDebugger.pdb
          ${{ github.workspace }}/build/bin/ChildDebugger.vsdconfig
          ${{ github.workspace }}/build/tests/bin/caller.exe
          ${{ github.workspace }}/build/tests/bin/caller.pdb
          ${{ github.workspace }}/build/tests/bin/callee.exe
          ${{ github.workspace }}/build/tests/bin/callee.pdb
          ${{ github.workspace }}/build/bin/info.txt

  deploy-head:
    name: "Deploy head"
    needs: build
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-head.yml
