name: Package

on:
  push

permissions:
  contents: write
  deployments: write

jobs:
  package:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install VSCE
        run: npm install -g @vscode/vsce

      - name: Install Dependencies
        run: npm install

      - name: Compile Extension
        run: npm run compile

      - name: Download concord extension
        uses: robinraju/release-downloader@v1.8
        with:
          repository: albertziegenhagel/childdebugger-concord
          tag: head
          fileName: childdebugger-concord-x86_64-windows.zip
          out-file-path: vsdbg-engine-extension
          extract: true

      - name: Package
        run: |
          rm vsdbg-engine-extension/childdebugger-concord-x86_64-windows.zip
          rm -r vsdbg-engine-extension/tests
          vsce package --target win32-x64 --pre-release
          mv childdebugger-win32-x64-*.vsix childdebugger-win32-x64.vsix

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with: 
          name: childdebugger-win32-x64
          path: ${{ github.workspace }}/*.vsix

  deploy-head:
    name: "Deploy head"
    needs: package
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-head.yml
